### ISSUE TITLE
Patch set checklist

### ISSUE THREAD

**Issue by alban** [kinvolk/fuse-userns-patches#1]
Patch set checklist:
- [x] Each patch has a "From" line in the commit message
- [x] Contain a description of the tests
- [x] List of remaining TODO in the cover letter
- [x] Link to previous version v4 on patchwork
- [x] "Changes since v4"
- [x] "This patchset is based on work by..." could be a the top, as introduction
- [x] Include a pointer to a git repo. I suggest to name the branch "dongsu/fuse-userns-v5-1" and not updating the branch once published
- [x] Remove patches unrelated to fuse: patch 12 (fuse does not use block device)

**Comment by dongsupark** [comment]
Updated the master branch.

The only missing pieces are weblinks to the previous versions of a couple of individual patches. They don't seem to exist in the previous patchsets. Either they got dropped meanwhile, or they were added only to the Ubuntu kernel tree. In these cases, I didn't add links in the commit messages.

**Comment by dongsupark** [comment]
Already done.
