### ISSUE TITLE
Patch set checklist for v6

### ISSUE THREAD

**Issue by alban** [kinvolk/fuse-userns-patches#2]
check list:

- [x] it has a cover letter
- [x] it compiles
- [x] it works
- [x] cc the correct lists and people
- [x] ./scripts/checkpatch.pl
- [x] preparing "Changes since v5"
- [ ] review comments from v5 were addressed

Previous check list from #1:

- [x] Each patch has a "From" line in the commit message
- [x] Contain a description of the tests
- [ ] List of remaining TODO in the cover letter
- [x] Link to previous version v4 on patchwork
- [x] "Changes since v4"
- [x] "This patchset is based on work by..." could be a the top, as introduction
- [x] Include a pointer to a git repo

/cc @dongsupark

**Comment by dongsupark** [comment]
It's being prepared in the branch, it's work-in-progress:
https://github.com/kinvolk/fuse-userns-patches/tree/dongsu/fuse-userns-v6

Since Eric has not reviewed the patchset v5, the prepared patchset v6 could be changed again in the future.
